### ISSUE TITLE
Keyboard shortcut conflict

### ISSUE THREAD

**Issue by zsakmany** [MariusAlch/vscode-json-to-ts#1]
Hello,
I found a little conflict with the shortcuts. It's not really an issue, I just want to leave it here for future reference and google searches.
The default `jsonToTs.fromClipboard` (`ctrl+alt+v`) shortcut conflicts with the `@` (`altgr+v`) character on hungarian keyboard, ususally you get the following error:
**Selected string is not a valid JSON**
Of course it's easy to fix, just change the shortcut for something else.

**Comment by MariusAlch** [comment]
Thanks for submitting the issue. I will have this conflict in mind and if this extension receives more issues like these then I will consider changing the shortcut, but currently changing the shortcut for 2300 people would be unwise and will leave a lot of people confused because of one edge case. 

I would suggest change the shortcut locally and/or use the extension from "Show all commands"(CTRL+SHIFT+P)

closing this issue for now.

**Comment by Lukasz196** [comment]
Hi,
Shortcut `alt + s` is in conflict with polish letter "ś".
